{
 "title": "Box Insight",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "服务名称", "query": { "query": "box_info" } },
   {
    "name": "instance",
    "label": "实例名称",
    "query": {
     "query": "box_info{job=~\"${job:pipe}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Server Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_server_request_begin_total{job=~\"${job:pipe}\",instance=~\"${instance:pipe}\"}[$__rate_interval])) by (job)",
       "legendFormat": "未处理 ({{job}})"
      },
      {
       "expr": "sum(irate(http_server_request_finish_total{job=~\"${job:pipe}\",instance=~\"${instance:pipe}\"}[$__rate_interval])) by (job)",
       "legendFormat": "已处理 ({{job}})"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(job) (irate(http_server_request_duration_seconds_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "Max ({{job}})"
      },
      {
       "expr": "avg by (job) (irate(http_server_request_duration_seconds_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "Avg ({{job}})"
      },
      {
       "expr": "min by (job) (irate(http_server_request_duration_seconds_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "Min ({{job}})"
      }
     ]
    },
    {
     "title": "P99 Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_request_duration_seconds{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", quantile=\"0.99\"}",
       "legendFormat": "{{job}} {{method}} {{url}}"
      }
     ]
    },
    {
     "title": "Request/Response Through",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job) (irate(http_server_request_size_bytes_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "Request ({{job}})"
      },
      {
       "expr": "sum by (job) (irate(http_server_response_size_bytes_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "Response ({{job}})"
      }
     ]
    },
    {
     "title": "Request error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_server_request_finish_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", status!=\"200\"}[$__rate_interval])) by (job)",
       "legendFormat": "状态码异常（{{job}}）"
      },
      {
       "expr": "sum(irate(http_server_request_finish_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", errcode!=\"0\"}[$__rate_interval])) by (job)",
       "legendFormat": "错误码异常（{{job}}）"
      }
     ]
    },
    {
     "title": "Request error detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(http_server_request_finish_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", status!=\"200\"}[$__rate_interval])) by (job, status,errcode,method,url)",
       "legendFormat": "{{job}} {{status}} {{errcode}} {{method}} {{url}}"
      },
      {
       "expr": "sum(irate(http_server_request_finish_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", errcode!=\"0\"}[$__rate_interval])) by (job, status,errcode,method,url)",
       "legendFormat": "{{job}} {{status}} {{errcode}} {{method}} {{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "正在处理中请求",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "http_client_request_in_process{job=~\"${job:pipe}\",instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{method}} - {{baseUrl}}{{url}}"
      }
     ]
    },
    {
     "title": "最近发送的请求",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(http_client_request_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval])) by (method,statusCode,baseUrl,url)",
       "legendFormat": "{{method}} - {{statusCode}} - {{baseUrl}}{{url}}"
      }
     ]
    },
    {
     "title": "失败的请求",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(http_client_request_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", statusCode!=\"200\"}[$__rate_interval])",
       "legendFormat": "{{method}} - {{statusCode}} - {{baseUrl}}{{url}}"
      },
      {
       "expr": "irate(http_client_request_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", error!=\"\"}[$__rate_interval])",
       "legendFormat": "{{method}} - {{error}} - {{baseUrl}}{{url}}"
      }
     ]
    },
    {
     "title": "耗时前10的请求",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": " topk(10, irate(http_client_request_seconds_sum{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "{{method}} {{baseUrl}}{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutine",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{job}} {{instance}}"
      }
     ]
    },
    {
     "title": "Gothread",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_threads{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{job}} {{instance}}"
      }
     ]
    },
    {
     "title": "GC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", quantile=~\"1|0.75\"}",
       "legendFormat": "{{job}} {{instance}} - {{quantile}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "总内存 {{job}} {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "堆内存 {{job}} {{instance}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "栈内存 {{job}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedule Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "最近执行情况（次数/分钟）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "increase(schedule_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", error=\"\", panic=\"\"}[1m])",
       "legendFormat": "成功 ({{job}}) - {{task}}"
      },
      {
       "expr": "increase(schedule_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", error!=\"\"}[1m])",
       "legendFormat": "错误 ({{job}}) - {{task}} - {{error}}"
      },
      {
       "expr": "increase(schedule_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", panic!=\"\"}[1m])",
       "legendFormat": "异常 ({{job}}) - {{task}} - {{panic}}"
      }
     ]
    },
    {
     "title": "成功率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(sum(irate(schedule_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", error=\"\", panic=\"\"}[$__rate_interval])) by (job) / sum(irate(schedule_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))  by (job)) by (job)",
       "legendFormat": "{{job}} ({{job}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Client Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "最近命令执行情况",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(redis_client_command_total{job=~\"${job:pipe}\",instance=~\"${instance:pipe}\", error!=\"\"}[$__rate_interval])",
       "legendFormat": "失败 ({{job}}) {{cmd}} - {{error}}"
      },
      {
       "expr": "irate(redis_client_command_total{job=~\"${job:pipe}\",instance=~\"${instance:pipe}\", error=\"\"}[$__rate_interval])",
       "legendFormat": "成功 ({{job}}) {{cmd}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "最近缓存查询次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(cache_hit_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval])",
       "legendFormat": "{{key}} ({{job}})"
      }
     ]
    },
    {
     "title": "缓存命中率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (irate(cache_hit_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\", hit=\"true\"}[$__rate_interval])) / sum by (job) (irate(cache_hit_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval]))",
       "legendFormat": "{{key}} ({{job}})"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Client Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "处理中的请求",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mongo_client_session_in_progress{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "最近处理请求",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(mongo_client_command_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval])",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "处理成功率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job,command,error)(irate(mongo_client_command_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\",error=\"\"}[$__rate_interval]))/(sum by (job,command,error)(irate(mongo_client_command_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}[$__rate_interval])))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "命令耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mongo_client_command_duration_seconds{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\"}",
       "legendFormat": "{{command}} - {{quantile}}"
      }
     ]
    },
    {
     "title": "失败命令",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongo_client_command_total{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\",error!=\"\"}[$__rate_interval])",
       "legendFormat": "{{command}} - {{error}}"
      }
     ]
    },
    {
     "title": "失败命令耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongo_client_command_duration_seconds{job=~\"${job:pipe}\", instance=~\"${instance:pipe}\",error!=\"\"}[$__rate_interval])",
       "legendFormat": "{{command}} - {{error}}"
      }
     ]
    }
   ]
  }
 ]
}